#!/bin/bash
#
# stow_all - Recreate my working environment by stowing all the files in my
# .dotfiles dir
#

#------------------------------------------------------------------------------
# Functions for setting up the necessary directories in the ~/.config directory
#------------------------------------------------------------------------------

# Nvim setup
config_nvim() {
	nvim_dir_path="$1"

	for subdir in autoload plugged; do
		nvim_subdirs="${nvim_dir_path}/${subdir}"
		if [[ -d "${nvim_subdirs}" ]]; then
			rm -rf "${nvim_subdirs}"/*
		fi
	done

	init_vim_path="${nvim_dir_path}/init.vim"
	if [[ -f "${init_vim_path}" ]]; then
		rm "${init_vim_path}"
	fi
}

# Delete config files if they exist
config_del() {
	full_path="$1"
	full_path_basename="$(basename ${full_path})"

	if [[ "${full_path_basename}" == nvim ]]; then
		config_nvim "${full_path}"
	else
		if [[ ! -f "${full_path}" ]]; then
			rm "${full_path}"/*
		else
			rm "${full_path}"
		fi
	fi
}

# Create the expected directory structure
create_dir_struct() {
	full_path="$1"
	full_path_basename="$(basename ${full_path})"

	if [[ "${full_path_basename}" == nvim ]]; then
		mkdir -p "${full_path}"/{autoload,plugged}
	elif [[ "${full_path_basename}" == ranger ]]; then
		mkdir -p "${full_path}"
	fi
}

# Main stow loop

# Set target directory
TARGET_DIR="/home/fahmi"

# The contents of each sub-directory in .dotfiles as well as the names of the
# applications to stow
CONTENTS=( .bashrc .zshrc .config/nvim .config/ranger .Rprofile .inputrc .tmux.conf \
	.Xmodmap .ycm_extra_conf.py )
APPS=( bash zsh nvim ranger R readline tmux xmodmap ycm_extra_conf )

# Stow the contents
END=$(( ${#APPS[@]} - 1 ))
for i in $(seq 0 $END); do
	FULL_PATH="${TARGET_DIR}/${CONTENTS[$i]}"
	if [[ -e "${FULL_PATH}" ]]; then
		config_del "${FULL_PATH}"
	else
		create_dir_struct "${FULL_PATH}"
	fi
	stow ${APPS[$i]}
done
